"""empty message

Revision ID: 278c9ab1290f
Revises: 
Create Date: 2022-06-28 14:47:05.504356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278c9ab1290f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('salt', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('venue', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eventid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
