"""empty message

Revision ID: 95903db2c9ae
Revises: 278c9ab1290f
Create Date: 2022-06-29 14:10:55.188972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95903db2c9ae'
down_revision = '278c9ab1290f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_dat', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('start_tim', sa.String(length=10), nullable=True))
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', mysql.DATETIME(), nullable=True))
    op.add_column('events', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.drop_column('events', 'start_tim')
    op.drop_column('events', 'end_dat')
    # ### end Alembic commands ###
