"""empty message

Revision ID: cf108977e83f
Revises: fb51b212830e
Create Date: 2022-06-29 14:31:15.053782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf108977e83f'
down_revision = 'fb51b212830e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('venue', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eventid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
