"""empty message

Revision ID: fb51b212830e
Revises: 80a7bd76d1fe
Create Date: 2022-06-29 14:30:42.302269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb51b212830e'
down_revision = '80a7bd76d1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('eventid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('venue', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('website_url', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('start_time', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], name='events_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eventid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
